targets:
  $default:
    builders:
      drift_dev:
        options:
          # このオプションは、drift_devでWebサポートを有効にするために使用できます。
          #
          # このオプションが設定されていない場合、drift_devはWebバックエンドを
          # 使用しているかどうかを自動検出しようとします。
          # 私たちは条件付きインポートを使用しているため、この自動検出が失敗する可能性があります。
          # このオプションを明示的に有効にすることで、この問題を回避できます。
          generate_web_worker: true