name: gasorin_app_final
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # --- sembast 関連パッケージ ---
  sembast: ^3.7.0
  sembast_web: ^2.3.0
  path_provider: ^2.1.3
  path: ^1.9.1

  # --- その他 ---
  provider: ^6.1.2
  geolocator: ^12.0.0
  flutter_local_notifications: ^17.2.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # build_runner と drift_dev は完全に不要
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true